version: "3.4"
services:
  www:
    image: node:19.9.0
    working_dir: /app
    command: >
      sh -c "npm install -g @angular/cli && ng serve --host 0.0.0.0 --disable-host-check"
    volumes:
      - ${PWD}/apps:/app:delegated