version: "3.4"
networks:
  proxylampy:
    external: true
services:
  www:
    image: node:20.3.1
    working_dir: /app
    command: >
      sh -c "npm install -g @angular/cli && ng serve --host 0.0.0.0 --disable-host-check"
    volumes:
      - ${PWD}/apps:/app:delegated
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.angular.rule=Host(`angular.traefik.me`)"
        - "traefik.http.routers.angular-tls.tls.domains[0].main=angular.traefik.me"
        - "traefik.http.routers.angular.tls=true"
        - "traefik.http.services.angular.loadbalancer.server.port=4200"
